[package]
name = "rust_stoic_quotes"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }  # Ensure "json" feature is enabled
tokio = { version = "1", features = ["full"] }
